AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Exclude:
  - 'spec/**/*'
